### ISSUE TITLE
Possible bug in surveyor virtual machine cleanup task scheduling

### ISSUE THREAD

**Issue by fritzo** [fritzo/pomagma#23]
Spurious early results indicated the VM-backed surveyor may miss occasional tasks during cleanup. To diagnose further, try the following:
<pre>
python -m pomagma init skrj  # or another theory
python -m pomagma update-theory skrj dry_run=True
</pre>
If all is working correctly, `update-theory` prints 'theory did not change'.

**Comment by fritzo** [comment]
<pre>
$ make batch-test
...
------------------------------------------------------------------------------
Testing skj
cd /home/fritz/fritzo/pomagma/data/test/debug/atlas/skj

POMAGMA_SIZE=1535 \
  POMAGMA_LOG_FILE=/home/fritz/fritzo/pomagma/data/test/debug/atlas/skj/test.log \
  POMAGMA_LOG_LEVEL=2 \
  /home/fritz/fritzo/pomagma/build/debug/src/surveyor/init \
  /home/fritz/fritzo/pomagma/data/test/debug/atlas/skj/0.h5 \
  /home/fritz/fritzo/pomagma/pomagma/theory/skj.symbols \
  /home/fritz/fritzo/pomagma/pomagma/theory/skj.facts \
  /home/fritz/fritzo/pomagma/pomagma/theory/skj.programs \
  /home/fritz/fritzo/pomagma/pomagma/language/skj.language \
  8
# took 80.8 sec
POMAGMA_SIZE=1535 \
  POMAGMA_LOG_FILE=/home/fritz/fritzo/pomagma/data/test/debug/atlas/skj/test.log \
  POMAGMA_LOG_LEVEL=2 \
  /home/fritz/fritzo/pomagma/build/debug/src/surveyor/survey \
  /home/fritz/fritzo/pomagma/data/test/debug/atlas/skj/0.h5 \
  /home/fritz/fritzo/pomagma/data/test/debug/atlas/skj/1.h5 \
  /home/fritz/fritzo/pomagma/pomagma/theory/skj.symbols \
  /home/fritz/fritzo/pomagma/pomagma/theory/skj.facts \
  /home/fritz/fritzo/pomagma/pomagma/theory/skj.programs \
  /home/fritz/fritzo/pomagma/pomagma/language/skj.language \
  8
# took 4.05 sec
theory changed
cd /home/fritz/fritzo/pomagma

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/fritz/fritzo/pomagma/src/make.py", line 189, in <module>
    parsable.dispatch()
  File "/home/fritz/fritzo/parsable/parsable.py", line 100, in dispatch
    parser(*args, **kwargs)
  File "/home/fritz/fritzo/parsable/parsable.py", line 53, in parser
    fun(*typed_args, **typed_kwargs)
  File "/home/fritz/fritzo/pomagma/src/make.py", line 122, in test_atlas
    _test_atlas(theory)
  File "/home/fritz/fritzo/pomagma/src/make.py", line 46, in _test_atlas
    assert not changed
AssertionError
make[1]: *** [batch-test] Error 1
make[1]: Leaving directory `/home/fritz/fritzo/pomagma'
make: *** [test] Error 2
</pre>
