### ISSUE TITLE
HDF5-DIAG Error

### ISSUE THREAD

**Issue by fritzo** [fritzo/pomagma#26]
Crash while exploring:
<pre>
7292    150383      INFO    Dumping structure to file temp.7281.region.queue/temp.7281.3.h5
7292    150420      INFO    done dumping structure
7292    150420      INFO    Clearing signature
7292    567478      ERROR   HDF5-DIAG: Error detected in HDF5 (1.8.11) thread 139657236969216:
  #000: ../../../src/H5T.c line 2142 in H5Tget_size(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type

        /home/fritz/fritzo/pomagma/include/pomagma/platform/hdf5.hpp : 57
        size_t pomagma::hdf5::type_size(const hid_t&)
</pre>
Traceback
<pre>
Thread 1 (Thread 0x7f047bfff700 (LWP 7357)):
#0  0x00007f04a9e60cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007f04a9e640d8 in __GI_abort () at abort.c:89
#2  0x00007f04ac069116 in pomagma::hdf5::type_size (type=@0x7f047bffda60: -1) at
 /home/fritz/fritzo/pomagma/include/pomagma/platform/hdf5.hpp:57
#3  0x00007f04ac071835 in pomagma::hdf5::Dataset::write_block<unsigned int> (this=this@entry=0x7f047bffdf30, source=std::vector of length 7066, capacity 16384 =
 {...}, offset=offset@entry=16030831) at /home/fritz/fritzo/pomagma/include/pomagma/platform/hdf5.hpp:609
#4  0x00007f04ac074f6a in pomagma::detail::dump<pomagma::BinaryFunction> (carrier=..., fun=..., file=..., arity="binary", name="COMP") at /home/fritz/fritzo/pomagma/include/pomagma/platform/structure.hpp:482
#5  0x00007f04ac0768ec in pomagma::detail::dump (signature=..., file=...) at /ho
me/fritz/fritzo/pomagma/include/pomagma/platform/structure.hpp:517
#6  0x00007f04ac0770b7 in pomagma::dump (signature=..., filename="temp.7281.region.queue/temp.7281.1.h5") at /home/fritz/fritzo/pomagma/include/pomagma/platform/structure.hpp:538
#7  0x00000000004228ef in pomagma::Server::trim(std::vector<pomagma::Server::TrimTask, std::allocator<pomagma::Server::TrimTask> > const&) [clone ._omp_fn.0] ()
 at /home/fritz/fritzo/pomagma/src/cartographer/server.cpp:72
#8  0x00007f04aa631826 in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#9  0x00007f04aa1f7182 in start_thread (arg=0x7f047bfff700) at pthread_create.c:312
#10 0x00007f04a9f2447d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
</pre>

**Comment by fritzo** [comment]
Abandoning HDF5 in favor of gzipped protobuf stream blobs.
